FROM mcr.microsoft.com/devcontainers/python:3.11
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libglib2.0-0 libsm6 libxext6 libxrender-dev \
    git curl unzip ca-certificates dcm2niix \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
